### ISSUE TITLE
bug(测试)

### ISSUE THREAD

**Issue by laf02240804** [laf02240804/study_github#2]
test

**Comment by laf02240804** [comment]
@lafhh 麻麻

**Comment by laf02240804** [comment]
@lafhh hdhdjj

**Comment by laf02240804** [comment]
😄

**Comment by laf02240804** [comment]
> 麻麻

dsaadsasd

**Comment by laf02240804** [comment]
https://github.com/laf02240804/study_github/issues/2#issuecomment-153056084

**Comment by laf02240804** [comment]
#3

**Comment by laf02240804** [comment]
#3

**Comment by lafhh** [comment]
@lafhh djdjdj

**Comment by laf02240804** [comment]
@lafhh alskdjflkads
![thumb_psu_1024](https://cloud.githubusercontent.com/assets/11388475/10943232/82c20566-834e-11e5-92aa-112be4c901b6.jpg)
